[terminal]
shell = "/usr/bin/zsh"

[window.padding]
x = 5
y = 5

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 1

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
size = 10

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#11121D"
foreground = "#a9b1d6"

[colors.normal]
black = "#32344a"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#787c99"

[colors.bright]
black = "#444b6a"
red = "#ff7a93"
green = "#b9f27c"
yellow = "#ff9e64"
blue = "#7da6ff"
magenta = "#bb9af7"
cyan = "#0db9d7"
white = "#acb0d0"

[selection]
save_to_clipboard = false

[general]
live_config_reload = true

[[keyboard.bindings]]
key = "Return"
mods = "Alt|Shift"
action = "SpawnnewInstance"
